print("
jlkfsjlkdgklgjs
skgjkdsjglkdjgksa
sjgdksjgksgjk
gsjgksjgjlkgjkdsjgkljkjgdksa
dkgjkdsajgksjgsdkjg
")
print("something")
print("something")
print("something")
print("something")
print("something")
print("something")
print("something")
